export const BASE_URL = "http://acme.com/api/"

//export const BEAR_TOKEN_OWNER = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJVc2VySWQiOiJlYTJlOGQxOS1kOWRkLTQ0N2MtOTQzZC1kOWZhZjBlZWFjNGMiLCJFbWFpbCI6Ik93bmVyMUBnbWFpbC5jb20iLCJodHRwOi8vc2NoZW1hcy5taWNyb3NvZnQuY29tL3dzLzIwMDgvMDYvaWRlbnRpdHkvY2xhaW1zL3JvbGUiOiJPd25lciIsImV4cCI6MTcwMTk5NzI1NCwiaXNzIjoiYmNoY2JjaGFzZGthY2Ftc2NuYXNrZGxuYXNkbWFzbGNhc2xkc2FuYWxjYXNsbmRhc2NtbGFza3NhbmMiLCJhdWQiOiJiY2hjYmNoYXNka2FjYW1zY25hc2tkbG5hc2RtYXNsY2FzbGRzYW5hbGNhc2xuZGFzY21sYXNrc2FuYyJ9.1hZ9hoshzYtBvQxeC4293HSfPpMztCX67k-SvLnl2Wg"

//export const BEAR_TOKEN_OWNER= 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJVc2VySWQiOiIzYmIzN2IyNS1hM2E1LTQ1ODQtOTIxNy1mMWQyZTk5ZTNlZTUiLCJFbWFpbCI6IkFkbWluQGdtYWlsLmNvbSIsImh0dHA6Ly9zY2hlbWFzLm1pY3Jvc29mdC5jb20vd3MvMjAwOC8wNi9pZGVudGl0eS9jbGFpbXMvcm9sZSI6IkFkbWluIiwiZXhwIjoxNzAyMDc4Nzg5LCJpc3MiOiJiY2hjYmNoYXNka2FjYW1zY25hc2tkbG5hc2RtYXNsY2FzbGRzYW5hbGNhc2xuZGFzY21sYXNrc2FuYyIsImF1ZCI6ImJjaGNiY2hhc2RrYWNhbXNjbmFza2RsbmFzZG1hc2xjYXNsZHNhbmFsY2FzbG5kYXNjbWxhc2tzYW5jIn0.eGRQR4qCuoL3VKHsL3kdFOZ6aTFyoxejJ_h72WtPbxM';

 const JWTTOKEN=()=>{
    return localStorage.getItem("Token");
}

export const BEAR_TOKEN=JWTTOKEN();

const ROLE=()=>{
    return localStorage.getItem("Role");
}

export const Role=ROLE();

const ID=()=>{
    return localStorage.getItem("Id");
}

export const Id=ID();